{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/21355",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21355/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21355/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21355/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/21355",
  "id": 1050389752,
  "node_id": "I_kwDOCFbutM4-m6z4",
  "number": 21355,
  "title": "Continuous testing fails to run any tests due to `ClassNotFoundException`",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 2955098535,
      "node_id": "MDU6TGFiZWwyOTU1MDk4NTM1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/continuous-testing",
      "name": "area/continuous-testing",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 2,
  "created_at": "2021-11-10T23:00:56Z",
  "updated_at": "2022-01-05T06:43:22Z",
  "closed_at": "2022-01-05T06:43:22Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nI'm getting the following exception when resuming/running tests:\r\n```\r\n2021-11-10 23:43:55,103 ERROR [io.qua.test] (Test runner thread) Internal error running tests: java.lang.RuntimeException: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests\r\n        at io.quarkus.deployment.dev.testing.JunitTestRunner.prepare(JunitTestRunner.java:416)\r\n        at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:83)\r\n        at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:335)\r\n        at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:294)\r\n        at java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests\r\n        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)\r\n        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)\r\n        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)\r\n        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)\r\n        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)\r\n        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:78)\r\n        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.discover(DefaultLauncherSession.java:81)\r\n        at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:46)\r\n        at io.quarkus.deployment.dev.testing.JunitTestRunner.prepare(JunitTestRunner.java:179)\r\n        ... 4 more\r\nCaused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'de.somecompany.someproject.register.tsp.connector.TspWebServiceTspConnectorTest'] resolution failed\r\n        at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)\r\n        at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)\r\n        at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)\r\n        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)\r\n        ... 12 more\r\nCaused by: java.lang.NoClassDefFoundError: de/tsystems/mms/someproject/register/persistence/entity/SomeKey\r\n        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)\r\n        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)\r\n        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)\r\n        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3439)\r\n        at java.base/java.lang.Class.getMethods(Class.java:2019)\r\n        at org.junit.platform.commons.util.ReflectionUtils.getDefaultMethods(ReflectionUtils.java:1518)\r\n        at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1491)\r\n        at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:1341)\r\n        at org.junit.platform.commons.util.ReflectionUtils.isMethodPresent(ReflectionUtils.java:1242)\r\n        at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.hasTestOrTestFactoryOrTestTemplateMethods(IsTestClassWithTests.java:50)\r\n        at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.test(IsTestClassWithTests.java:46)\r\n        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:67)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)\r\n        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\r\n        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)\r\n        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)\r\n        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)\r\n        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)\r\n        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\r\n        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)\r\n        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)\r\n        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)\r\n        ... 17 more\r\nCaused by: java.lang.ClassNotFoundException: de.somecompany.someproject.register.persistence.entity.SomeKey\r\n        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:429)\r\n        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)\r\n        ... 42 more\r\n```\r\n`SomeKey` is just an `@Embeddable` from our `register-core` module. Dev mode is started in the `register-server` module and we have 6 other modules that the server module depends on as well.\r\n\r\nI tried continuous testing various times before 2.4 and got similar exceptions, but mentioning other classes.\r\nBut since before 2.4 there was no way to run tests from upstream modules (and our server module has no own tests), the setup was a bit different there; dev mode was run in other modules that had test-jars in the mix, which is probably not directly comparable.\r\n\r\n### Expected behavior\r\n\r\nNo exceptions, test should be executed.\r\n\r\n### Actual behavior\r\n\r\nClassNotFoundException\r\n\r\n### How to Reproduce?\r\n\r\nSo far I have been unable to reproduce this with smaller setups and my project is closed source.\r\n\r\n@stuartwdouglas asked me to create an issue regardless: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/PR.20Review/near/255134078\r\n\r\n\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\nLinux XXX 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux\r\n\r\n### Output of `java -version`\r\n\r\nOpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing) (also happened with Java 11)\r\n\r\n### GraalVM version (if different from Java)\r\n\r\n_No response_\r\n\r\n### Quarkus version or git rev\r\n\r\n2.4.1.Final\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\nApache Maven 3.8.1\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/21355/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/21355/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
