{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/34912",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/34912/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/34912/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/34912/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/34912",
  "id": 1815606051,
  "node_id": "I_kwDOCFbutM5sN_Mj",
  "number": 34912,
  "title": "Failed auth with blocking authentication & a custom authentication failure mapper cause HTTP/2 error",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1282139374,
      "node_id": "MDU6TGFiZWwxMjgyMTM5Mzc0",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/security",
      "name": "area/security",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/255",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/255",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/255/labels",
    "id": 9565017,
    "node_id": "MI_kwDOCFbutM4AkfNZ",
    "number": 255,
    "title": "3.3.0.CR1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 310,
    "state": "closed",
    "created_at": "2023-06-21T07:35:19Z",
    "updated_at": "2024-05-17T05:53:43Z",
    "due_on": null,
    "closed_at": "2023-08-09T11:23:12Z"
  },
  "comments": 9,
  "created_at": "2023-07-21T10:57:41Z",
  "updated_at": "2023-07-27T11:29:44Z",
  "closed_at": "2023-07-27T11:29:40Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nWhen the following combination is enabled:\r\n1. The client request is HTTP/2\r\n1. `quarkus.smallrye-jwt.blocking-authentication` is `true`\r\n2. Authentication is enabled (e.g. SmallRye JWT)\r\n3. Authentication throws exception\r\n\r\nThe request fails with `Request has already been read` and results in a `500` response instead of the mapped exception response.\n\n### Expected behavior\n\nHTTP/2 connections correctly support blocking authentication and authentication exception mappers. \n\n### Actual behavior\n\nAn exception is thrown with `Request has already been read` and a `500` response is returned instead of the response returned by the exception mapper.\n\n### How to Reproduce?\n\n[blocking-auth-mapper-fail-2.16.8.zip](https://github.com/quarkusio/quarkus/files/12122834/blocking-auth-mapper-fail-2.16.8.zip)\r\n[blocking-auth-mapper-fail-3.2.1.zip](https://github.com/quarkusio/quarkus/files/12122835/blocking-auth-mapper-fail-3.2.1.zip)\r\n\r\nRunning the included test reproduces the issue in both `2.16` and `3.2` series.\n\n### Output of `uname -a` or `ver`\n\nmacOS 13.4\n\n### Output of `java -version`\n\nJava 17.0.4\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\n3.2.1 & 2.16.8\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nGradle 8.1\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/34912/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/34912/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
