{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/35336",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35336/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35336/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35336/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/35336",
  "id": 1848720816,
  "node_id": "I_kwDOCFbutM5uMT2w",
  "number": 35336,
  "title": "Dev Services for Microsoft SQL server does not enable XA transactions when transaction type is XA",
  "labels": [
    {
      "id": 985346622,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjI=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/enhancement",
      "name": "kind/enhancement",
      "color": "a2eeef",
      "default": false,
      "description": "New feature or request"
    },
    {
      "id": 1633508165,
      "node_id": "MDU6TGFiZWwxNjMzNTA4MTY1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/narayana",
      "name": "area/narayana",
      "color": "0366d6",
      "default": false,
      "description": "Transactions / Narayana"
    }
  ],
  "state": "open",
  "locked": false,
  "milestone": null,
  "comments": 5,
  "created_at": "2023-08-13T20:00:24Z",
  "updated_at": "2023-09-15T15:49:58Z",
  "closed_at": null,
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nI have application with Narayana JTA extension, using XA transactions and when 2 JDBC XA resources are involved, transaction always fail in DEV mode, for XA transactions are not enabled in SQL server.\r\n\r\n### Expected behavior\r\n\r\nIt would be very nice if dev svcs could enable it for me, it can be done like this `container.execInContainer(\r\n                        \"/opt/mssql-tools/bin/sqlcmd\", \"-S\", \"localhost\", \"-U\", getUsername(), \"-P\", getPassword(), \"-Q\",\r\n                        \"EXEC sp_sqljdbc_xa_install\");`\r\n\r\n### Actual behavior\r\n\r\nTransaction fails and exception is logged out\r\n```\r\n2023-08-13 21:47:59,230 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016027: Local XARecoveryModule.xaRecovery got XA exception XAException.XAER_RMERR: javax.transaction.xa.XAException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to create the XA control connection. Error: \"Could not find stored procedure 'master..xp_sqljdbc_xa_init_ex'.\"\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.DTC_XA_Interface(SQLServerXAResource.java:757)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.recover(SQLServerXAResource.java:841)\r\n\tat io.agroal.narayana.RecoveryXAResource.recover(RecoveryXAResource.java:31)\r\n\tat com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoveryFirstPass(XARecoveryModule.java:735)\r\n\tat com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:249)\r\n\tat com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:191)\r\n\tat com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:770)\r\n\tat com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)\r\n\r\n2023-08-13 21:47:59,237 WARN  [com.arj.ats.jta] (Periodic Recovery) ARJUNA016027: Local XARecoveryModule.xaRecovery got XA exception XAException.XAER_RMERR: javax.transaction.xa.XAException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to create the XA control connection. Error: \"Could not find stored procedure 'master..xp_sqljdbc_xa_init_ex'.\"\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.DTC_XA_Interface(SQLServerXAResource.java:757)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.recover(SQLServerXAResource.java:841)\r\n\tat io.agroal.narayana.RecoveryXAResource.recover(RecoveryXAResource.java:31)\r\n\tat com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoveryFirstPass(XARecoveryModule.java:735)\r\n\tat com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:249)\r\n\tat com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:191)\r\n\tat com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:770)\r\n\tat com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)\r\n\r\n2023-08-13 21:48:01,332 WARN  [com.arj.ats.jta] (executor-thread-1) ARJUNA016061: TransactionImple.enlistResource - XAResource.start returned: XAException.XAER_RMERR for < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a0000b9:a38f:64d9336e:7, node_name=rhbq-qe, branch_uid=0:ffff0a0000b9:a38f:64d9336e:45, subordinatenodename=null, eis_name=0 >: javax.transaction.xa.XAException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to create the XA control connection. Error: \"The connection is closed.\"\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.DTC_XA_Interface(SQLServerXAResource.java:757)\r\n\tat com.microsoft.sqlserver.jdbc.SQLServerXAResource.start(SQLServerXAResource.java:791)\r\n\tat io.agroal.narayana.BaseXAResource.start(BaseXAResource.java:150)\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:661)\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:422)\r\n\tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:93)\r\n\tat io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:252)\r\n\tat io.agroal.pool.DataSource.getConnection(DataSource.java:86)\r\n\tat org.acme.GreetingResource.createTable(GreetingResource.java:39)\r\n\tat org.acme.GreetingResource.hello(GreetingResource.java:32)\r\n\tat org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)\r\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\r\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\r\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)\r\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)\r\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\r\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\r\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\r\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\n\r\n2023-08-13 21:48:01,335 WARN  [com.arj.ats.jta] (executor-thread-1) ARJUNA016138: Failed to enlist XA resource io.agroal.narayana.BaseXAResource@1620ee94: jakarta.transaction.SystemException: TransactionImple.enlistResource - XAResource.start ARJUNA016054: could not register transaction: < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a0000b9:a38f:64d9336e:7, node_name=rhbq-qe, branch_uid=0:ffff0a0000b9:a38f:64d9336e:45, subordinatenodename=null, eis_name=0 >\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:714)\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.enlistResource(TransactionImple.java:422)\r\n\tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:93)\r\n\tat io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:252)\r\n\tat io.agroal.pool.DataSource.getConnection(DataSource.java:86)\r\n\tat org.acme.GreetingResource.createTable(GreetingResource.java:39)\r\n\tat org.acme.GreetingResource.hello(GreetingResource.java:32)\r\n\tat org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)\r\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\r\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\r\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)\r\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)\r\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\r\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\r\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\r\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\n\r\n2023-08-13 21:48:01,412 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 4166535d-5154-4425-8e99-d52d8c1244de-1: java.lang.RuntimeException: java.sql.SQLException: Exception in association of connection to existing transaction\r\n\tat org.acme.GreetingResource.createTable(GreetingResource.java:44)\r\n\tat org.acme.GreetingResource.hello(GreetingResource.java:33)\r\n\tat org.acme.GreetingResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source)\r\n\tat org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)\r\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)\r\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)\r\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)\r\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\r\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\r\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\r\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: java.sql.SQLException: Exception in association of connection to existing transaction\r\n\tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:100)\r\n\tat io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:252)\r\n\tat io.agroal.pool.DataSource.getConnection(DataSource.java:86)\r\n\tat org.acme.GreetingResource.createTable(GreetingResource.java:39)\r\n\t... 12 more\r\nCaused by: com.arjuna.ats.jta.exceptions.RollbackException: ARJUNA016081: The transaction implementation threw a RollbackException\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionSynchronizationRegistryImple.registerInterposedSynchronization(TransactionSynchronizationRegistryImple.java:144)\r\n\tat jakarta.transaction.NarayanaJtaProducers_ProducerMethod_transactionSynchronizationRegistry_6c1ae1f6c0015764ef2a5d1837652baa9054bdb5_ClientProxy.registerInterposedSynchronization(Unknown Source)\r\n\tat io.agroal.narayana.NarayanaTransactionIntegration.associate(NarayanaTransactionIntegration.java:82)\r\n\t... 15 more\r\nCaused by: jakarta.transaction.RollbackException: ARJUNA016083: Cannot register synchronization because the transaction is in aborted state\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.registerSynchronizationImple(TransactionImple.java:395)\r\n\tat com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionSynchronizationRegistryImple.registerInterposedSynchronization(TransactionSynchronizationRegistryImple.java:140)\r\n\t... 17 more\r\n```\r\n\r\n### How to Reproduce?\r\n\r\nReproducer:\r\n\r\n- `git clone git@github.com:michalvavrik/quarkus-narayana-jta-mssql-reproducer.git`\r\n- `cd quarkus-narayana-jta-mssql-reproducer`\r\n- `mvn clean test`\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\nLinux fedora 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux\r\n\r\n### Output of `java -version`\r\n\r\nOpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)\r\n\r\n### GraalVM version (if different from Java)\r\n\r\n22.3\r\n\r\n### Quarkus version or git rev\r\n\r\n3.2.4.Final and 999-SNAPSHOT\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\nApache Maven 3.9.3\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/35336/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/35336/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
