{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/36250",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36250/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36250/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36250/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/36250",
  "id": 1922319655,
  "node_id": "I_kwDOCFbutM5ylEUn",
  "number": 36250,
  "title": "TestStatus error usability",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1375177076,
      "node_id": "MDU6TGFiZWwxMzc1MTc3MDc2",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/testing",
      "name": "area/testing",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "milestone": null,
  "comments": 3,
  "created_at": "2023-10-02T17:19:45Z",
  "updated_at": "2023-10-12T07:15:12Z",
  "closed_at": null,
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nUpon the first occurrance of an exception in a test class TestStatus.testErrorCause will be set to that exception.  This state is retained for subsequent passing tests, but it overwritten by additional test failures.\r\n\r\nAfter an initial failure to determine if an individual test is failing this means you have to correlate whether the failure stacktrace contains the current test method.\n\n### Expected behavior\n\nMore than likely on a passing test method the testErrorCause state should be cleared.\n\n### Actual behavior\n\ntestErrorCause stays populated even if a subsequent test passes.\n\n### How to Reproduce?\n\nhttps://github.com/keycloak/keycloak/pull/23641/files#diff-2630e65f8b32c7c9b6249637101ba1d0221727b8c6e0ec482d7f29c76d4e9e45R276 shows the keycloak usage of QuarkusTestAfterEachCallback and the workaround to detect exactly which test is failing.\n\n### Output of `uname -a` or `ver`\n\n_No response_\n\n### Output of `java -version`\n\n_No response_\n\n### GraalVM version (if different from Java)\n\n_No response_\n\n### Quarkus version or git rev\n\n3.2.6\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\n_No response_\n\n### Additional information\n\nIf the intention of testErrorCause is to be retained across passing tests, could there be another method added to quickly determine if the current test method was the one that failed?",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/36250/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/36250/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
