{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/38934",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38934/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38934/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38934/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/38934",
  "id": 2147242894,
  "node_id": "I_kwDOCFbutM5__FOO",
  "number": 38934,
  "title": "Agroal Data Source Health check failing for reactive data source",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1283619446,
      "node_id": "MDU6TGFiZWwxMjgzNjE5NDQ2",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/smallrye",
      "name": "area/smallrye",
      "color": "0366d6",
      "default": false,
      "description": ""
    },
    {
      "id": 2236032169,
      "node_id": "MDU6TGFiZWwyMjM2MDMyMTY5",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/health",
      "name": "area/health",
      "color": "0366d6",
      "default": false,
      "description": ""
    },
    {
      "id": 2955097332,
      "node_id": "MDU6TGFiZWwyOTU1MDk3MzMy",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/agroal",
      "name": "area/agroal",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/312",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/312",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/312/labels",
    "id": 10606558,
    "node_id": "MI_kwDOCFbutM4Aodfe",
    "number": 312,
    "title": "3.8.1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 44,
    "state": "closed",
    "created_at": "2024-02-26T16:57:35Z",
    "updated_at": "2024-02-28T11:29:26Z",
    "due_on": null,
    "closed_at": "2024-02-28T11:29:26Z"
  },
  "comments": 7,
  "created_at": "2024-02-21T16:55:19Z",
  "updated_at": "2024-03-12T09:44:43Z",
  "closed_at": "2024-02-24T10:17:49Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\n\nWhen application defines a mix of datasources (Reactive & JDBC), health check fails with below error.\r\n\r\nWorks fine with Quarkus Version < 3.7. I think issue is introduced by https://github.com/quarkusio/quarkus/pull/38108\r\n\r\nSample config:\r\n\r\nquarkus.datasource.db-kind=postgresql\r\nquarkus.datasource.metrics.enabled=true\r\nquarkus.datasource.jdbc=false\r\nquarkus.datasource.reactive=true\r\n## additional datasource for flyway migration\r\nquarkus.datasource.migds.db-kind=postgresql\r\nquarkus.datasource.migds.reactive=false\r\nquarkus.datasource.migds.jdbc=true\r\nquarkus.flyway.migds.clean-at-start=false\r\nquarkus.flyway.migds.create-schemas=false\r\nquarkus.flyway.migds.migrate-at-start=true\r\nquarkus.flyway.migds.repair-at-start=true\r\n\n\n### Expected behavior\n\nHealth check should return health status of both the datasources.\r\n\r\n\n\n### Actual behavior\n\nStart app using quarkus:dev\r\n\r\nTest URL http://[localhost:8080/q/health](http://localhost:8080/q/health)\r\n\r\n```\r\n{\r\n    \"status\": \"DOWN\",\r\n    \"checks\": [\r\n        {\r\n            \"name\": \"io.quarkus.agroal.runtime.health.DataSourceHealthCheck_ClientProxy\",\r\n            \"status\": \"DOWN\",\r\n            \"data\": {\r\n                \"exceptionClass\": \"java.lang.IllegalArgumentException\",\r\n                \"exceptionMessage\": \"No datasource named '<default>' exists\",\r\n                \"rootCause\": \"No datasource named '<default>' exists\"\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"Reactive PostgreSQL connections health check\",\r\n            \"status\": \"UP\",\r\n            \"data\": {\r\n                \"<default>\": \"UP\"\r\n            }\r\n        }\r\n    ]\r\n}\r\n```\r\n\r\n\r\nErrors in Logs\r\n\r\n```\r\nSRHCK01000: Error processing Health Checks: java.lang.IllegalArgumentException: No datasource named '<default>' exists\r\n        at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:165)\r\n        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:145)\r\n        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:142)\r\n        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)\r\n        at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:142)\r\n        at io.quarkus.agroal.runtime.health.DataSourceHealthCheck.init(DataSourceHealthCheck.java:49)\r\n\r\n```\n\n### How to Reproduce?\n\nEasy to reproduce. Getting started sample with below config produces the error.\r\n\r\n```\r\nquarkus.datasource.db-kind=postgresql\r\nquarkus.datasource.metrics.enabled=true\r\nquarkus.datasource.jdbc=false\r\nquarkus.datasource.reactive=true\r\n## additional datasource for flyway migration\r\nquarkus.datasource.migds.db-kind=postgresql\r\nquarkus.datasource.migds.reactive=false\r\nquarkus.datasource.migds.jdbc=true\r\nquarkus.flyway.migds.clean-at-start=false\r\nquarkus.flyway.migds.create-schemas=false\r\nquarkus.flyway.migds.migrate-at-start=true\r\nquarkus.flyway.migds.repair-at-start=true\r\n```\r\n\r\nSample app: https://github.com/mvmandapati/code-with-quarkus\n\n### Output of `uname -a` or `ver`\n\nLinux\n\n### Output of `java -version`\n\nopenjdk 21.0.2 2024-01-16\n\n### Quarkus version or git rev\n\n3.7.3\n\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\n\nMaven 3.9.1\n\n### Additional information\n\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/38934/reactions",
    "total_count": 1,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 1
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/38934/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
