{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/39652",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39652/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39652/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39652/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/39652",
  "id": 2203600596,
  "node_id": "I_kwDOCFbutM6DWEbU",
  "number": 39652,
  "title": "Conflict between grpc and hibernate when throwing StatusRuntimeException",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1273026509,
      "node_id": "MDU6TGFiZWwxMjczMDI2NTA5",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/persistence",
      "name": "area/persistence",
      "color": "FBCA04",
      "default": false,
      "description": "OBSOLETE, DO NOT USE"
    },
    {
      "id": 2062531368,
      "node_id": "MDU6TGFiZWwyMDYyNTMxMzY4",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/grpc",
      "name": "area/grpc",
      "color": "0366d6",
      "default": false,
      "description": "gRPC"
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": null,
  "comments": 8,
  "created_at": "2024-03-23T01:20:59Z",
  "updated_at": "2024-04-17T12:26:59Z",
  "closed_at": "2024-04-17T12:26:58Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nI want to throw a StatusRuntimeException when an issue occured while executing a remote call.\r\nThe exception can be enriched by adding details as ErrorInfo.\r\n\r\nWhen the service is Transactional (can be needed when downloading a file from a blob datasource) we can notice two issues:\r\n1. The exception message is duplicated\r\n2. The list containing the details is empty (and should not be)\r\n\r\n### Expected behavior\r\n\r\nThe exception can be caught by the client. The exception contains all the detail defined by the server.\r\n\r\n### Actual behavior\r\n\r\n1. The exception message is duplicated (and should not be)\r\n2. The detail is empty (and should not be)\r\n\r\n### How to Reproduce?\r\n\r\n1. git clone https://github.com/dcdh/quarkus-grcp-transactional-issue-reproducer\r\n2. Run the tests\r\n\r\nTo make the test worked you should comment this dependency:\r\n```xml\r\n        <dependency>\r\n            <groupId>io.quarkus</groupId>\r\n            <artifactId>quarkus-hibernate-orm</artifactId>\r\n        </dependency>\r\n```\r\n\r\nBut I need it.\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\nLinux 2a02-8428-dff8-c601-234b-8c10-a3c4-2308.rev.sfr.net 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64 GNU/Linux\r\n\r\n### Output of `java -version`\r\n\r\nopenjdk version \"17.0.9\" 2023-10-17\r\n\r\n### Quarkus version or git rev\r\n\r\n3.8.3\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\n_No response_\r\n\r\n### Additional information\r\n\r\nI guess using `@Transactional` trigger an interceptor. This interceptor does not handle well the StatusRuntimeException in case of grpc.",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/39652/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/39652/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
