{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/40574",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/40574/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/40574/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/40574/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/40574",
  "id": 2290987933,
  "node_id": "I_kwDOCFbutM6IjbOd",
  "number": 40574,
  "title": "When Using Liquibase with \"quarkus.liquibase.clean-at-start=true\" a RuntimeException Is Thrown in Quarkus 3.10.0",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1956491735,
      "node_id": "MDU6TGFiZWwxOTU2NDkxNzM1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/liquibase",
      "name": "area/liquibase",
      "color": "0366d6",
      "default": false,
      "description": ""
    },
    {
      "id": 2497075451,
      "node_id": "MDU6TGFiZWwyNDk3MDc1NDUx",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/native-image",
      "name": "area/native-image",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/343",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/343",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/343/labels",
    "id": 11392625,
    "node_id": "MI_kwDOCFbutM4ArdZx",
    "number": 343,
    "title": "3.13.1",
    "description": "",
    "creator": {
      "login": "gsmet",
      "id": 1279749,
      "node_id": "MDQ6VXNlcjEyNzk3NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1279749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gsmet",
      "html_url": "https://github.com/gsmet",
      "followers_url": "https://api.github.com/users/gsmet/followers",
      "following_url": "https://api.github.com/users/gsmet/following{/other_user}",
      "gists_url": "https://api.github.com/users/gsmet/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gsmet/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gsmet/subscriptions",
      "organizations_url": "https://api.github.com/users/gsmet/orgs",
      "repos_url": "https://api.github.com/users/gsmet/repos",
      "events_url": "https://api.github.com/users/gsmet/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gsmet/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 61,
    "state": "closed",
    "created_at": "2024-08-01T17:33:59Z",
    "updated_at": "2024-08-14T12:55:49Z",
    "due_on": null,
    "closed_at": "2024-08-07T13:20:46Z"
  },
  "comments": 4,
  "created_at": "2024-05-11T16:51:32Z",
  "updated_at": "2024-08-01T17:36:37Z",
  "closed_at": "2024-07-25T17:22:33Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nAt App startup an exception is thrown and the program exits, when using Liquibase with `quarkus.liquibase.clean-at-start=true` set.\r\nThis happens at least with Postgresql and H2.\r\nThe issue didn't occur before Quarkus 3.10.0\r\nThe problem happens for a local as well as an in-container build.\r\n\r\nFor Postgres, the following error is logged:\r\n\r\n```\r\nINFO  [liq.command] (main) Logging exception.\r\nERROR: Exception Details\r\nERROR: Exception Primary Class:  PSQLException\r\nERROR: Exception Primary Reason:  ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\nERROR: Exception Primary Source:  PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2)\r\nINFO  [liq.command] (main) Command execution complete\r\n2024-05-11 18:11:33,653 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]):\r\n```\r\n\r\nand the following exception is thrown:\r\n\r\n```\r\njava.lang.RuntimeException: Failed to start quarkus\r\n\tat io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)\r\n\tat io.quarkus.runtime.Application.start(Application.java:101)\r\n\tat io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)\r\n\tat io.quarkus.runtime.Quarkus.run(Quarkus.java:71)\r\n\tat io.quarkus.runtime.Quarkus.run(Quarkus.java:44)\r\n\tat io.quarkus.runtime.Quarkus.run(Quarkus.java:124)\r\n\tat io.quarkus.runner.GeneratedMain.main(Unknown Source)\r\nCaused by: java.lang.IllegalStateException: Error starting Liquibase\r\n\tat io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:90)\r\n\tat io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)\r\n\tat io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)\r\n\t... 7 more\r\nCaused by: liquibase.exception.DatabaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:1028)\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:1009)\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:994)\r\n\tat io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:71)\r\n\t... 9 more\r\nCaused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\n\tat liquibase.command.CommandScope.execute(CommandScope.java:257)\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:1026)\r\n\t... 12 more\r\nCaused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\n\tat liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:407)\r\n\tat liquibase.command.core.DropAllCommandStep.run(DropAllCommandStep.java:120)\r\n\tat liquibase.command.CommandScope.execute(CommandScope.java:219)\r\n\t... 13 more\r\nCaused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\n\tat liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:62)\r\n\tat liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:372)\r\n\t... 15 more\r\nCaused by: liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\n\tat liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:101)\r\n\tat liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:337)\r\n\tat liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:305)\r\n\tat liquibase.lockservice.StandardLockService.lambda$releaseLock$6(StandardLockService.java:372)\r\n\tat liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$query$1(ChangelogJdbcMdcListener.java:55)\r\n\tat liquibase.Scope.child(Scope.java:199)\r\n\tat liquibase.Scope.child(Scope.java:175)\r\n\tat liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:55)\r\n\t... 16 more\r\nCaused by: org.postgresql.util.PSQLException: ERROR: relation \"public.databasechangeloglock\" does not exist\r\n  Position: 8\r\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)\r\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)\r\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)\r\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)\r\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)\r\n\tat org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)\r\n\tat org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)\r\n\tat org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)\r\n\tat org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:275)\r\n\tat io.agroal.pool.wrapper.StatementWrapper.executeUpdate(StatementWrapper.java:120)\r\n\tat liquibase.executor.jvm.JdbcExecutor$1UpdateStatementCallback.doInStatement(JdbcExecutor.java:328)\r\n\tat liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:80)\r\n\t... 23 more\r\n```\r\n\r\nFor H2 the log contains:\r\n\r\n```\r\nINFO  [liq.command] (main) Logging exception.\r\nERROR: Exception Details\r\nERROR: Exception Primary Class:  JdbcSQLSyntaxErrorException\r\nERROR: Exception Primary Reason:  Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\nERROR: Exception Primary Source:  H2 2.2.224 (2023-09-17)\r\n2024-05-11 17:43:26,697 INFO  [liq.command] (main) Command execution complete\r\n2024-05-11 17:43:26,727 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]):\r\n```\r\n\r\nand the exception is:\r\n\r\n```\r\njava.lang.RuntimeException: Failed to start quarkus\r\n\tat io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)\r\n\tat io.quarkus.runtime.Application.start(Application.java:101)\r\n\tat io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)\r\n\tat io.quarkus.runtime.Quarkus.run(Quarkus.java:71)\r\n\tat io.quarkus.runtime.Quarkus.run(Quarkus.java:44)\r\n\tat io.quarkus.runtime.Quarkus.run(Quarkus.java:124)\r\n\tat io.quarkus.runner.GeneratedMain.main(Unknown Source)\r\nCaused by: java.lang.IllegalStateException: Error starting Liquibase\r\n\tat io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:90)\r\n\tat io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)\r\n\tat io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)\r\n\t... 7 more\r\nCaused by: liquibase.exception.DatabaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:1028)\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:1009)\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:994)\r\n\tat io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:71)\r\n\t... 9 more\r\nCaused by: liquibase.exception.CommandExecutionException: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\n\tat liquibase.command.CommandScope.execute(CommandScope.java:257)\r\n\tat liquibase.Liquibase.dropAll(Liquibase.java:1026)\r\n\t... 12 more\r\nCaused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\n\tat liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:407)\r\n\tat liquibase.command.core.DropAllCommandStep.run(DropAllCommandStep.java:120)\r\n\tat liquibase.command.CommandScope.execute(CommandScope.java:219)\r\n\t... 13 more\r\nCaused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\n\tat liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:62)\r\n\tat liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:372)\r\n\t... 15 more\r\nCaused by: liquibase.exception.DatabaseException: Error executing SQL UPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\n\tat liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:101)\r\n\tat liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:337)\r\n\tat liquibase.executor.jvm.JdbcExecutor.update(JdbcExecutor.java:305)\r\n\tat liquibase.lockservice.StandardLockService.lambda$releaseLock$6(StandardLockService.java:372)\r\n\tat liquibase.executor.jvm.ChangelogJdbcMdcListener.lambda$query$1(ChangelogJdbcMdcListener.java:55)\r\n\tat liquibase.Scope.child(Scope.java:199)\r\n\tat liquibase.Scope.child(Scope.java:175)\r\n\tat liquibase.executor.jvm.ChangelogJdbcMdcListener.query(ChangelogJdbcMdcListener.java:55)\r\n\t... 16 more\r\nCaused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabelle \"DATABASECHANGELOGLOCK\" nicht gefunden (diese Datenbank ist leer)\r\nTable \"DATABASECHANGELOGLOCK\" not found (this database is empty); SQL statement:\r\nUPDATE PUBLIC.DATABASECHANGELOGLOCK SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1 [42104-224]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:514)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:489)\r\n\tat org.h2.message.DbException.get(DbException.java:223)\r\n\tat org.h2.message.DbException.get(DbException.java:199)\r\n\tat org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8051)\r\n\tat org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8045)\r\n\tat org.h2.command.Parser.getTableOrViewNotFoundDbException(Parser.java:8029)\r\n\tat org.h2.command.Parser.readTableOrView(Parser.java:8024)\r\n\tat org.h2.command.Parser.readTableOrView(Parser.java:7990)\r\n\tat org.h2.command.Parser.readSimpleTableFilter(Parser.java:1094)\r\n\tat org.h2.command.Parser.parseUpdate(Parser.java:1018)\r\n\tat org.h2.command.Parser.parsePrepared(Parser.java:765)\r\n\tat org.h2.command.Parser.parse(Parser.java:592)\r\n\tat org.h2.command.Parser.parse(Parser.java:564)\r\n\tat org.h2.command.Parser.prepareCommand(Parser.java:483)\r\n\tat org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)\r\n\tat org.h2.server.TcpServerThread.process(TcpServerThread.java:289)\r\n\tat org.h2.server.TcpServerThread.run(TcpServerThread.java:191)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\r\n\r\n\tat org.h2.engine.SessionRemote.readException(SessionRemote.java:650)\r\n\tat org.h2.engine.SessionRemote.done(SessionRemote.java:619)\r\n\tat org.h2.command.CommandRemote.prepare(CommandRemote.java:78)\r\n\tat org.h2.command.CommandRemote.<init>(CommandRemote.java:50)\r\n\tat org.h2.engine.SessionRemote.prepareCommand(SessionRemote.java:487)\r\n\tat org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)\r\n\tat org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:190)\r\n\tat org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:147)\r\n\tat io.agroal.pool.wrapper.StatementWrapper.executeUpdate(StatementWrapper.java:120)\r\n\tat liquibase.executor.jvm.JdbcExecutor$1UpdateStatementCallback.doInStatement(JdbcExecutor.java:328)\r\n\tat liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:80)\r\n\t... 23 more\r\n```\r\n\r\n### Expected behavior\r\n\r\nThe DB is migrated and the app successfully started.\r\n\r\n### Actual behavior\r\n\r\nAn Exception is thrown, the DB isn't migrated and the application exits.\r\n\r\n### How to Reproduce?\r\n\r\nTo reproduce the error with Postgresql:\r\n\r\n1. Use the `liquibase-quickstart` from the `quarkus-quickstarts` repo.\r\n2. Change `<artifactId>quarkus-jdbc-h2</artifactId>` to `<artifactId>quarkus-jdbc-postgresql</artifactId>` in `pom.xml`.\r\n3. Change the data source to `%prod.quarkus.datasource.db-kind=postgresql` and the url to `%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test` in `application.properties`.\r\n4. Run a DB-instance e.g.: ` docker run -d --rm --name=test-db -p 0.0.0.0:5432:5432 -e POSTGRES_USER=sa -e POSTGRES_PASSWORD=sa -e POSTGRES_DB=test postgres:16.2`\r\n5. Compile the app: `mvn clean package -Dnative -DskipTests`.\r\n6. Run: `./target/liquibase-quickstart-1.0.0-SNAPSHOT-runner`.\r\n\r\nYou can use similar steps to reproduce the error with H2.\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\nDarwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64\r\n\r\n### Output of `java -version`\r\n\r\njava 21.0.3 2024-04-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)\r\n\r\n### Mandrel or GraalVM version (if different from Java)\r\n\r\n_No response_\r\n\r\n### Quarkus version or git rev\r\n\r\n3.10.0\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\nApache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/40574/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/40574/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
