{
  "url": "https://api.github.com/repos/quarkusio/quarkus/issues/42067",
  "repository_url": "https://api.github.com/repos/quarkusio/quarkus",
  "labels_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42067/labels{/name}",
  "comments_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42067/comments",
  "events_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42067/events",
  "html_url": "https://github.com/quarkusio/quarkus/issues/42067",
  "id": 2424701015,
  "node_id": "I_kwDOCFbutM6QhgBX",
  "number": 42067,
  "title": "App with Infinispan fails after changes in JarFileReference that rarely results in illegal state after changes on ReadWriteLock",
  "labels": [
    {
      "id": 985346620,
      "node_id": "MDU6TGFiZWw5ODUzNDY2MjA=",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/kind/bug",
      "name": "kind/bug",
      "color": "d73a4a",
      "default": false,
      "description": "Something isn't working"
    },
    {
      "id": 1282122953,
      "node_id": "MDU6TGFiZWwxMjgyMTIyOTUz",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/infinispan",
      "name": "area/infinispan",
      "color": "0366d6",
      "default": false,
      "description": "Infinispan"
    },
    {
      "id": 1654772125,
      "node_id": "MDU6TGFiZWwxNjU0NzcyMTI1",
      "url": "https://api.github.com/repos/quarkusio/quarkus/labels/area/kubernetes",
      "name": "area/kubernetes",
      "color": "0366d6",
      "default": false,
      "description": ""
    }
  ],
  "state": "closed",
  "locked": false,
  "milestone": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/milestones/341",
    "html_url": "https://github.com/quarkusio/quarkus/milestone/341",
    "labels_url": "https://api.github.com/repos/quarkusio/quarkus/milestones/341/labels",
    "id": 11324154,
    "node_id": "MI_kwDOCFbutM4ArMr6",
    "number": 341,
    "title": "3.14.0.CR1",
    "description": "",
    "creator": {
      "login": "quarkusbot",
      "id": 61254497,
      "node_id": "MDQ6VXNlcjYxMjU0NDk3",
      "avatar_url": "https://avatars.githubusercontent.com/u/61254497?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/quarkusbot",
      "html_url": "https://github.com/quarkusbot",
      "followers_url": "https://api.github.com/users/quarkusbot/followers",
      "following_url": "https://api.github.com/users/quarkusbot/following{/other_user}",
      "gists_url": "https://api.github.com/users/quarkusbot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarkusbot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarkusbot/subscriptions",
      "organizations_url": "https://api.github.com/users/quarkusbot/orgs",
      "repos_url": "https://api.github.com/users/quarkusbot/repos",
      "events_url": "https://api.github.com/users/quarkusbot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarkusbot/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 192,
    "state": "closed",
    "created_at": "2024-07-17T08:04:03Z",
    "updated_at": "2024-08-29T19:11:05Z",
    "due_on": null,
    "closed_at": "2024-08-14T11:26:07Z"
  },
  "comments": 16,
  "created_at": "2024-07-23T09:22:05Z",
  "updated_at": "2024-07-31T07:48:02Z",
  "closed_at": "2024-07-31T07:47:58Z",
  "active_lock_reason": null,
  "body": "### Describe the bug\r\n\r\nI have application with Infinispan extension that is deployed to Openshift using the OpenShift extension. Lately I have experienced flakiness when Infinipan library performs service loading on application startup. My colleague @jedla97 discovered that this started happen after https://github.com/quarkusio/quarkus/pull/40942.\r\n\r\n### Expected behavior\r\n\r\nNo race.\r\n\r\n### Actual behavior\r\n\r\nApplication startup fails with exception:\r\n\r\n```\r\n03:16:59,364 INFO  [two] 03:16:57,505 Failed to initialize a channel. Closing: [id: 0xd1e053bd]: java.lang.IllegalStateException: The reference counter cannot be negative, found: -1\r\n03:16:59,364 INFO  [two] \tat io.quarkus.bootstrap.runner.JarFileReference.release(JarFileReference.java:58)\r\n03:16:59,364 INFO  [two] \tat io.quarkus.bootstrap.runner.JarFileReference.consumeSharedJarFile(JarFileReference.java:129)\r\n03:16:59,364 INFO  [two] \tat io.quarkus.bootstrap.runner.JarFileReference.withJarFile(JarFileReference.java:107)\r\n03:16:59,364 INFO  [two] \tat io.quarkus.bootstrap.runner.JarResource.getResourceURL(JarResource.java:89)\r\n03:16:59,364 INFO  [two] \tat io.quarkus.bootstrap.runner.RunnerClassLoader.findResources(RunnerClassLoader.java:265)\r\n03:16:59,364 INFO  [two] \tat java.base/java.lang.ClassLoader.getResources(ClassLoader.java:1473)\r\n03:16:59,364 INFO  [two] \tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1203)\r\n03:16:59,364 INFO  [two] \tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)\r\n03:16:59,364 INFO  [two] \tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)\r\n03:16:59,364 INFO  [two] \tat java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)\r\n03:16:59,364 INFO  [two] \tat java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)\r\n03:16:59,364 INFO  [two] \tat org.infinispan.commons.util.SaslUtils.getFactories(SaslUtils.java:58)\r\n03:16:59,365 INFO  [two] \tat org.infinispan.commons.util.SaslUtils.getSaslClientFactories(SaslUtils.java:49)\r\n03:16:59,365 INFO  [two] \tat org.infinispan.client.hotrod.impl.transport.netty.ChannelInitializer.getSaslClientFactory(ChannelInitializer.java:227)\r\n03:16:59,365 INFO  [two] \tat org.infinispan.client.hotrod.impl.transport.netty.ChannelInitializer.initAuthentication(ChannelInitializer.java:204)\r\n03:16:59,365 INFO  [two] \tat org.infinispan.client.hotrod.impl.transport.netty.ChannelInitializer.initChannel(ChannelInitializer.java:110)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:608)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:45)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1460)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1114)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:649)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:513)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:485)\r\n03:16:59,365 INFO  [two] \tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\r\n03:16:59,365 INFO  [two] \tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\r\n03:16:59,365 INFO  [two] \tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)\r\n03:16:59,365 INFO  [two] \tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)\r\n03:16:59,366 INFO  [two] \tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\r\n03:16:59,366 INFO  [two] \tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n03:16:59,366 INFO  [two] \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n03:16:59,366 INFO  [two] \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n03:16:59,366 INFO  [two] \tat java.base/java.lang.Thread.run(Thread.java:840)\r\n03:16:59,366 INFO  [two] 03:16:57,517 ISPN004007: Exception encountered. Retry 0 out of 0: io.netty.channel.StacklessClosedChannelException\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source)\r\n03:16:59,366 INFO  [two] 03:16:57,517 ISPN004007: Exception encountered. Retry 0 out of 0: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: ts-qhdkqxqyjo-infinispan-cluster.datagrid-cluster.svc.cluster.local/172.30.48.250:11222\r\n03:16:59,366 INFO  [two] Caused by: java.net.ConnectException: Connection refused\r\n03:16:59,366 INFO  [two] \tat java.base/sun.nio.ch.Net.pollConnect(Native Method)\r\n03:16:59,366 INFO  [two] \tat java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)\r\n03:16:59,366 INFO  [two] \tat java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\r\n03:16:59,366 INFO  [two] \tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\r\n03:16:59,367 INFO  [two] \tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)\r\n03:16:59,367 INFO  [two] \tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n03:16:59,367 INFO  [two] \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n03:16:59,367 INFO  [two] \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n03:16:59,367 INFO  [two] \tat java.base/java.lang.Thread.run(Thread.java:840)\r\n```\r\n\r\n### How to Reproduce?\r\n\r\nReproducer:\r\n\r\n0. have OpenShift cluster up and running, be logged in there\r\n1. `git clone git@github.com:quarkus-qe/quarkus-test-suite.git`\r\n2. `git checkout e4056763aecf9a048b89a0e4f2b5ae0e9a98da25` (that just because I don't know if I won't disable the test, you likely can skip this step)\r\n3. `quarkus-test-suite/infinispan-client`\r\n4. `mvn clean verify -Dopenshift -Dit.test=OperatorOpenShiftInfinispanCountersIT -Doc.reruns=0`\r\n\r\nBut I'll be honest with you, our Jenkins has **by far** more success in reproducing it than I do on my workstation. I have never actually seen this exception outside of Jenkins logs.\r\n\r\n### Output of `uname -a` or `ver`\r\n\r\nFedora 40\r\n\r\n### Output of `java -version`\r\n\r\n17.0.10, vendor: Red Hat, Inc., runtime: /qa/tools/opt/x86_64/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64\r\n\r\n### Quarkus version or git rev\r\n\r\n999-SNAPSHOT\r\n\r\n### Build tool (ie. output of `mvnw --version` or `gradlew --version`)\r\n\r\nApache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)\r\n\r\n### Additional information\r\n\r\n_No response_",
  "reactions": {
    "url": "https://api.github.com/repos/quarkusio/quarkus/issues/42067/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/quarkusio/quarkus/issues/42067/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
